# Generated by Django 4.2.7 on 2023-11-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, verbose_name='用户名')),
                ('user_password', models.IntegerField(max_length=64, verbose_name='密码')),
                ('user_age', models.IntegerField(verbose_name='年龄')),
                ('user_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('user_depart', models.CharField(max_length=24, verbose_name='部门')),
                ('user_time', models.TimeField(max_length=24, verbose_name='入职时间')),
            ],
        ),
    ]
