# Generated by Django 4.2.7 on 2023-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.IntegerField(verbose_name='密码'),
        ),
    ]
