# Generated by Django 4.2.7 on 2023-11-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_userinfo_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_time',
            field=models.DateField(max_length=24, verbose_name='入职时间'),
        ),
    ]
